spring:
  datasource:
    url: jdbc:mysql://node16/book?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456


rxjava2jdbc:
  pool:
    size: 10