apiVersion: v1
kind: Pod
metadata:
  name: readinessprobe-pod
  labels:
    app: readinessprobe-pod
spec:
  containers:
    - name: readinessprobe-pod
      image: nginx:1.17.10-alpine
      imagePullPolicy: IfNotPresent
      readinessProbe:
        httpGet:
          port: 80
          path: /index1.html
        initialDelaySeconds: 1
        periodSeconds: 3
  restartPolicy: Always